image: jangrewe/gitlab-ci-android

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew
cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

stages:
  - build
  - test

lintDebug:
  stage: build
  script:
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
#debug apk
assembleDebug:
  stage: build
  script:
    - ./gradlew --stacktrace clean assembleDebug
  artifacts:
    paths:
      - app/build/outputs/
#release apk
build:
  stage: build
  script:
    - ./gradlew --stacktrace clean assembleRelease
  artifacts:
    paths:
      - app/build/outputs/
#test
coverageTests:
  stage: test
  script:
    - ./gradlew -Pci --console=plain jacocoTestReport

debugTests:
  stage: test
  script:
    - ./gradlew -Pci --console=plain :app:testDebug